OLED_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes

## via stuff
VIA_ENABLE = no
VIAL_ENABLE = no
VIALRGB_ENABLE = no
RGB_MATRIX_ENABLE = no
